package com.main.pojo;
// Generated Jan 2, 2017 5:30:01 PM by Hibernate Tools 4.3.1



/**
 * TblPatient generated by hbm2java
 */
public class TblPatient  implements java.io.Serializable {


     private Integer id;
     private String firstName;
     private String lastName;
     private String mobile;
     private String age;
     private String sex;
     private String address;
     private String spousename;
     private String spouseage;
     private String reference;
     private String timeaddmission;
     private String dateaddmission;

    public TblPatient() {
    }

    public TblPatient(String firstName, String lastName, String mobile, String age, String sex, String address, String spousename, String spouseage, String reference, String timeaddmission, String dateaddmission) {
       this.firstName = firstName;
       this.lastName = lastName;
       this.mobile = mobile;
       this.age = age;
       this.sex = sex;
       this.address = address;
       this.spousename = spousename;
       this.spouseage = spouseage;
       this.reference = reference;
       this.timeaddmission = timeaddmission;
       this.dateaddmission = dateaddmission;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getFirstName() {
        return this.firstName;
    }
    
    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }
    public String getLastName() {
        return this.lastName;
    }
    
    public void setLastName(String lastName) {
        this.lastName = lastName;
    }
    public String getMobile() {
        return this.mobile;
    }
    
    public void setMobile(String mobile) {
        this.mobile = mobile;
    }
    public String getAge() {
        return this.age;
    }
    
    public void setAge(String age) {
        this.age = age;
    }
    public String getSex() {
        return this.sex;
    }
    
    public void setSex(String sex) {
        this.sex = sex;
    }
    public String getAddress() {
        return this.address;
    }
    
    public void setAddress(String address) {
        this.address = address;
    }
    public String getSpousename() {
        return this.spousename;
    }
    
    public void setSpousename(String spousename) {
        this.spousename = spousename;
    }
    public String getSpouseage() {
        return this.spouseage;
    }
    
    public void setSpouseage(String spouseage) {
        this.spouseage = spouseage;
    }
    public String getReference() {
        return this.reference;
    }
    
    public void setReference(String reference) {
        this.reference = reference;
    }
    public String getTimeaddmission() {
        return this.timeaddmission;
    }
    
    public void setTimeaddmission(String timeaddmission) {
        this.timeaddmission = timeaddmission;
    }
    public String getDateaddmission() {
        return this.dateaddmission;
    }
    
    public void setDateaddmission(String dateaddmission) {
        this.dateaddmission = dateaddmission;
    }




}


