package com.main.pojo;
// Generated Dec 30, 2016 1:45:05 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * TblPatient generated by hbm2java
 */
public class TblPatient  implements java.io.Serializable {


     private Integer id;
     private String firstName;
     private String lastName;
     private String address;
     private String phoneNo;
     private String age;
     private String sex;
     private String spouseName;
     private String spouseAge;
     private String reference;
     private Date dateAddmission;
     private Date dateDischarge;
     private Date timeAddmission;

    public TblPatient() {
    }

    public TblPatient(String firstName, String lastName, String address, String phoneNo, String age, String sex, String spouseName, String spouseAge, String reference, Date dateAddmission, Date dateDischarge, Date timeAddmission) {
       this.firstName = firstName;
       this.lastName = lastName;
       this.address = address;
       this.phoneNo = phoneNo;
       this.age = age;
       this.sex = sex;
       this.spouseName = spouseName;
       this.spouseAge = spouseAge;
       this.reference = reference;
       this.dateAddmission = dateAddmission;
       this.dateDischarge = dateDischarge;
       this.timeAddmission = timeAddmission;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getFirstName() {
        return this.firstName;
    }
    
    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }
    public String getLastName() {
        return this.lastName;
    }
    
    public void setLastName(String lastName) {
        this.lastName = lastName;
    }
    public String getAddress() {
        return this.address;
    }
    
    public void setAddress(String address) {
        this.address = address;
    }
    public String getPhoneNo() {
        return this.phoneNo;
    }
    
    public void setPhoneNo(String phoneNo) {
        this.phoneNo = phoneNo;
    }
    public String getAge() {
        return this.age;
    }
    
    public void setAge(String age) {
        this.age = age;
    }
    public String getSex() {
        return this.sex;
    }
    
    public void setSex(String sex) {
        this.sex = sex;
    }
    public String getSpouseName() {
        return this.spouseName;
    }
    
    public void setSpouseName(String spouseName) {
        this.spouseName = spouseName;
    }
    public String getSpouseAge() {
        return this.spouseAge;
    }
    
    public void setSpouseAge(String spouseAge) {
        this.spouseAge = spouseAge;
    }
    public String getReference() {
        return this.reference;
    }
    
    public void setReference(String reference) {
        this.reference = reference;
    }
    public Date getDateAddmission() {
        return this.dateAddmission;
    }
    
    public void setDateAddmission(Date dateAddmission) {
        this.dateAddmission = dateAddmission;
    }
    public Date getDateDischarge() {
        return this.dateDischarge;
    }
    
    public void setDateDischarge(Date dateDischarge) {
        this.dateDischarge = dateDischarge;
    }
    public Date getTimeAddmission() {
        return this.timeAddmission;
    }
    
    public void setTimeAddmission(Date timeAddmission) {
        this.timeAddmission = timeAddmission;
    }




}


