package com.main.pojo;
// Generated Dec 30, 2016 1:45:05 PM by Hibernate Tools 4.3.1



/**
 * TblTreatmentadvise generated by hbm2java
 */
public class TblTreatmentadvise  implements java.io.Serializable {


     private Integer id;
     private String drugName;
     private String genericName;
     private String doses;
     private String duration;
     private String timing;

    public TblTreatmentadvise() {
    }

    public TblTreatmentadvise(String drugName, String genericName, String doses, String duration, String timing) {
       this.drugName = drugName;
       this.genericName = genericName;
       this.doses = doses;
       this.duration = duration;
       this.timing = timing;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getDrugName() {
        return this.drugName;
    }
    
    public void setDrugName(String drugName) {
        this.drugName = drugName;
    }
    public String getGenericName() {
        return this.genericName;
    }
    
    public void setGenericName(String genericName) {
        this.genericName = genericName;
    }
    public String getDoses() {
        return this.doses;
    }
    
    public void setDoses(String doses) {
        this.doses = doses;
    }
    public String getDuration() {
        return this.duration;
    }
    
    public void setDuration(String duration) {
        this.duration = duration;
    }
    public String getTiming() {
        return this.timing;
    }
    
    public void setTiming(String timing) {
        this.timing = timing;
    }




}


